// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoApi.DataAccess;

#nullable disable

namespace TodoApi.DataAccess.Migrations
{
    [DbContext(typeof(TodoDbContext))]
    partial class TodoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TodoApi.Model.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Due")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Created = new DateTime(2022, 2, 9, 23, 50, 54, 585, DateTimeKind.Local).AddTicks(4567),
                            Description = "Learn C# from tutorial",
                            Due = new DateTime(2022, 2, 14, 23, 50, 54, 585, DateTimeKind.Local).AddTicks(4574),
                            Status = 0,
                            Title = "Learn C#"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            Created = new DateTime(2022, 2, 9, 23, 50, 54, 585, DateTimeKind.Local).AddTicks(4579),
                            Description = "Learn bootstrap from tutorial",
                            Due = new DateTime(2022, 2, 16, 23, 50, 54, 585, DateTimeKind.Local).AddTicks(4580),
                            Status = 0,
                            Title = "Learn bootstrap"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            Created = new DateTime(2022, 2, 9, 23, 50, 54, 585, DateTimeKind.Local).AddTicks(4581),
                            Description = "Learn Anguler from tutorial",
                            Due = new DateTime(2022, 2, 12, 23, 50, 54, 585, DateTimeKind.Local).AddTicks(4581),
                            Status = 0,
                            Title = "Learn Anguler"
                        });
                });

            modelBuilder.Entity("TodoApi.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "John Doe"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Willim Max "
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Charith Roshan"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Allon Mark "
                        });
                });

            modelBuilder.Entity("TodoApi.Model.Todo", b =>
                {
                    b.HasOne("TodoApi.Models.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });
#pragma warning restore 612, 618
        }
    }
}
